# Generated by Django 4.2.1 on 2023-05-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('down_link', models.URLField()),
                ('down_time', models.DateTimeField(auto_now=True)),
                ('down_type', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Download_history',
            },
        ),
    ]
